version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=aluno_20201214010016
      - POSTGRES_PASSWORD=7063
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5439'
volumes:
  postgres: